name: inception

services:
  mariadb:
    image: mariadb
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: ./requirements/mariadb/.env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - inception
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  wordpress:
    image: wordpress
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    env_file: ./requirements/wordpress/.env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    networks: 
      - inception
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
      
  nginx:
    image: nginx
    build:
      context: ./requirements/nginx
    container_name: nginx
    env_file: ./requirements/nginx/.env
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "8443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 1s

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge
