services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    image: mariadb
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - wp_db:/var/lib/mysql
    networks:
      - inception

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
    image: wordpress
    restart: on-failure
    env_file:
      - .env
    secrets:
      - db_password
    depends_on:
      - mariadb
    volumes:
      - wp_files:/var/www/html
    networks:
      - inception

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
    image: nginx
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - wordpress
    ports:
      - "8443:443"
    volumes:
      - wp_files:/var/www/html:ro
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nabbas/data/mariadb
  wp_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nabbas/data/wordpress

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
