name: inception

services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: ./requirements/mariadb/.env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - inception
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    env_file: ./requirements/wordpress/.env
    secrets:
      - db_password
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    networks: 
      - inception

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress

networks:
  inception:
    driver: bridge
