name: inception

services:
  mariadb:
    image: mariadb
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: ./.env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - inception

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

volumes:
  mariadb_data:

networks:
  inception:
    driver: bridge
