name: inception

services:
  mariadb:
    build: 
      context: ./requirements/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: ./.env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - inception

  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: on-failure
    env_file: ./.env
    depends_on:
      - mariadb
    volumes:
      - wp_data:/var/www/html
    networks: 
      - inception

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DATA_DIR}/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${HOST_DATA_DIR}/wordpress

networks:
  inception:
    driver: bridge
