name: inception

services:
  mariadb:
    image: mariadb
    build: 
      context: ./aws/mariadb
    container_name: mariadb
    restart: on-failure
    env_file: ./aws/mariadb/.env
    volumes:
      - mariadb_data:/var/lib/mariadb
    networks:
      - inception
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  wordpress:
    image: wordpress
    build:
      context: ./aws/wordpress
    container_name: wordpress
    restart: on-failure
    env_file: ./aws/wordpress/.env
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - wp_data:/var/www/html
    networks: 
      - inception
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
      
  nginx:
    image: nginx
    build:
      context: ./aws/nginx
    container_name: nginx
    env_file: ./aws/nginx/.env
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception
    healthcheck:
      test: ["CMD", "bash", "/usr/local/bin/healthcheck.sh"]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 1s

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress

networks:
  inception:
    driver: bridge
